version: '3.8'

services:
  database:
    container_name: task-database
    image: postgres:13-alpine
    command: ["postgres", "-c", "log_statement=all", "-c", "log_destination=stderr"]
    environment:
      - POSTGRES_USER=task
      - POSTGRES_PASSWORD=task
      - POSTGRES_DB=task
    ports: 
      - 5432:5432
    volumes:
      - database:/var/lib/postgresql/data
volumes:
  database: